# generated by datamodel-codegen:
#   filename:  airway.json
#   timestamp: 2024-12-18T15:51:27+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from uid import UUID


class Geometry(BaseModel):
    type: str
    coordinates: List[List[float]]


class AirwayGeometry(BaseModel):
    geometry: Geometry


class Deviation(BaseModel):
    geometry: Geometry


class AirwayJunctionDetail(BaseModel):
    airway: AirwayGeometry
    deviation: Deviation


class AirwayJunction(BaseModel):
    id: str
    name: str
    type: str
    airways: List[AirwayJunctionDetail]


class AirwaySection(BaseModel):
    id: str
    name: str
    airway_point_ids: List[str]


class SingleAirway(BaseModel):
    id: str
    name: str
    junctions: List[AirwayJunction]
    sections: List[AirwaySection]


class Airway(BaseModel):
    administrator_id: UUID
    business_number: int
    airways: List[SingleAirway]


class AirwayDefinition(BaseModel):
    """
    A class used to represent the definition of an airway.
    Attributes
    ----------
    airway : Airway
        An instance of the Airway class representing the airway details.
    """

    id: UUID
    airway: Airway


# class AerialCorridorRead(BaseModel):
#     "A class to read data from the Aerial Corridor table"

#     url: str
#     min_cell_level: int
#     max_cell_level: int
#     start_datetime: str
#     end_datetime: str
#     created_at: str
#     updated_at: str


# class AerialCorridorWrite(BaseModel):
#     "A class to write data to the Aerial Corridor table"

#     id: str
#     url: str
#     min_cell_level: int
#     max_cell_level: int
#     start_datetime: str
#     end_datetime: str



# class GetAirwayDefinition(BaseModel):
#     """Get Airways Definition"""

#     raise NotImplementedError


# class QueryAirwayDefinitionParameters(BaseModel):
#     """Query all Airway Definitions for an area of interest"""

#     raise NotImplementedError


# class CreateOrUpdateAirways(BaseModel):
#     """Create or update Airway Definition"""
#     raise NotImplementedError

# class PutAirwaysDefinitionParameters(BaseModel):
#     """Put airways definition parameters"""
#     raise NotImplementedError
